FROM ubuntu

RUN apt-get -y update && apt-get -y upgrade

RUN apt-get install -y python3

RUN apt-get install -y g++

RUN apt-get install default-jre -y

RUN mkdir /home/user

WORKDIR /home/user

RUN mkdir cppLang/ python/ java/

CMD [ "bash" ]